name: Package

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build-wheel:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install build tooling
        run: |
          python -m pip install --upgrade pip
          python -m pip install build

      - name: Build distribution artifacts
        run: python -m build
